version: '3'
services:
  ingress-trafikverket:
    image: diwise/ingress-trafikverket:latest
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - context-broker
    environment:
      TFV_API_AUTH_KEY: $TFV_API_AUTH_KEY
      TFV_API_URL: $TFV_API_URL
      ROADACCIDENT_ENABLED: 'true'
      CONTEXT_BROKER_URL: 'http://context-broker:8080'


  context-broker:
    image: 'ghcr.io/diwise/context-broker:prod-9f3b4f349f72c95af4d91ff2ff838066f209b842'
    restart: always
    depends_on:
      - orion-ld
    environment:
      CONTEXT_BROKER_CLIENT_DEBUG: 'true'
    volumes:
      - ./configs/context-broker.yaml:/opt/diwise/config/default.yaml
      - ./configs/context-broker-auth.rego:/opt/diwise/config/authz.rego
    ports:
      - '8081:8080'


  orion-ld:
    image: 'quay.io/fiware/orion-ld@sha256:a65adbface4d5467add735d01c7204951e3c474ef8fc901fbd3a2af285beafea'
    restart: always
    command: [ '-experimental' ]
    environment:
      ORIONLD_MONGO_HOST: 'mongodb'
      ORIONLD_MONGO_USER: 'admin'
      ORIONLD_MONGO_PASSWORD: 'password'
      ORIONLD_LOG_FOR_HUMANS: 'TRUE'
      ORIONLD_TROE:	'FALSE'
      ORIONLD_DISABLE_FILE_LOG: 'TRUE'
    depends_on:
      - mongodb
    ports:
      - '8082:1026'


  mongodb:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27017'
    command: --nojournal --quiet
    volumes:
      - mongo-db:/data
  

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'admin'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
      ME_CONFIG_BASICAUTH_USERNAME: ''
    depends_on:
        - mongodb
    ports:
      - '8083:8081'

volumes:
  mongo-db: ~
