version: '3'
services:
  ingress-trafikverket:
    image: iot-for-tillgenglighet/ingress-trafikverket:latest
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - TFV_API_AUTH_KEY=$TFV_API_AUTH_KEY
  
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

volumes:
  rabbitmq_data:
    driver: local
