version: '3'
services:
  ingress-trafikverket:
    image: diwise/ingress-trafikverket:latest
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - context-broker
    environment:
      TFV_API_AUTH_KEY: $TFV_API_AUTH_KEY
      TFV_API_URL: $TFV_API_URL
      SDL_KARTA_URL: $SDL_KARTA_URL
      CITYWORK_ENABLED: 'true'
      ROADACCIDENT_ENABLED: 'true'
      CONTEXT_BROKER_URL: 'http://context-broker:8080'


  context-broker:
    image: 'ghcr.io/diwise/context-broker@sha256:53bb3e9ca15164afd3e873c5ac8e56e40e107caa9cb99c47d5a6c748a5dc4bfb'
    restart: always
    depends_on:
      - orion-ld
    volumes:
      - ./configs/context-broker.yaml:/opt/diwise/config/default.yaml
    ports:
      - '8081:8080'


  orion-ld:
    image: 'quay.io/fiware/orion-ld@sha256:ea838e5b405170b6d42af9035a30454a21870f7f3738db73da27585bf6a478b3'
    restart: always
    environment:
      ORIONLD_MONGO_HOST: 'mongodb'
      ORIONLD_MONGO_USER: 'admin'
      ORIONLD_MONGO_PASSWORD: 'password'
      ORIONLD_LOG_FOR_HUMANS: 'TRUE'
      ORIONLD_TROE:	'FALSE'
      ORIONLD_DISABLE_FILE_LOG: 'TRUE'
    depends_on:
      - mongodb
    ports:
      - '8082:1026'


  mongodb:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27017'
    command: --nojournal --quiet
    volumes:
      - mongo-db:/data
  

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'admin'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
      ME_CONFIG_BASICAUTH_USERNAME: ''
    depends_on:
        - mongodb
    ports:
      - '8083:8081'

volumes:
  mongo-db: ~
