// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package roadaccidents

import (
	"context"
	"sync"
)

// Ensure, that RoadAccidentSvcMock does implement RoadAccidentSvc.
// If this is not the case, regenerate this file with moq.
var _ RoadAccidentSvc = &RoadAccidentSvcMock{}

// RoadAccidentSvcMock is a mock implementation of RoadAccidentSvc.
//
//	func TestSomethingThatUsesRoadAccidentSvc(t *testing.T) {
//
//		// make and configure a mocked RoadAccidentSvc
//		mockedRoadAccidentSvc := &RoadAccidentSvcMock{
//			StartFunc: func(ctx context.Context) (chan struct{}, error) {
//				panic("mock out the Start method")
//			},
//			getAndPublishRoadAccidentsFunc: func(ctx context.Context, lastChangeID string) (string, error) {
//				panic("mock out the getAndPublishRoadAccidents method")
//			},
//			getRoadAccidentsFromTFVFunc: func(ctx context.Context, lastChangeID string) ([]byte, error) {
//				panic("mock out the getRoadAccidentsFromTFV method")
//			},
//			publishRoadAccidentToContextBrokerFunc: func(ctx context.Context, dev tfvDeviation, deleted bool) error {
//				panic("mock out the publishRoadAccidentToContextBroker method")
//			},
//		}
//
//		// use mockedRoadAccidentSvc in code that requires RoadAccidentSvc
//		// and then make assertions.
//
//	}
type RoadAccidentSvcMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context) (chan struct{}, error)

	// getAndPublishRoadAccidentsFunc mocks the getAndPublishRoadAccidents method.
	getAndPublishRoadAccidentsFunc func(ctx context.Context, lastChangeID string) (string, error)

	// getRoadAccidentsFromTFVFunc mocks the getRoadAccidentsFromTFV method.
	getRoadAccidentsFromTFVFunc func(ctx context.Context, lastChangeID string) ([]byte, error)

	// publishRoadAccidentToContextBrokerFunc mocks the publishRoadAccidentToContextBroker method.
	publishRoadAccidentToContextBrokerFunc func(ctx context.Context, dev tfvDeviation, deleted bool) error

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// getAndPublishRoadAccidents holds details about calls to the getAndPublishRoadAccidents method.
		getAndPublishRoadAccidents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LastChangeID is the lastChangeID argument value.
			LastChangeID string
		}
		// getRoadAccidentsFromTFV holds details about calls to the getRoadAccidentsFromTFV method.
		getRoadAccidentsFromTFV []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LastChangeID is the lastChangeID argument value.
			LastChangeID string
		}
		// publishRoadAccidentToContextBroker holds details about calls to the publishRoadAccidentToContextBroker method.
		publishRoadAccidentToContextBroker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dev is the dev argument value.
			Dev tfvDeviation
			// Deleted is the deleted argument value.
			Deleted bool
		}
	}
	lockStart                              sync.RWMutex
	lockgetAndPublishRoadAccidents         sync.RWMutex
	lockgetRoadAccidentsFromTFV            sync.RWMutex
	lockpublishRoadAccidentToContextBroker sync.RWMutex
}

// Start calls StartFunc.
func (mock *RoadAccidentSvcMock) Start(ctx context.Context) (chan struct{}, error) {
	if mock.StartFunc == nil {
		panic("RoadAccidentSvcMock.StartFunc: method is nil but RoadAccidentSvc.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedRoadAccidentSvc.StartCalls())
func (mock *RoadAccidentSvcMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// getAndPublishRoadAccidents calls getAndPublishRoadAccidentsFunc.
func (mock *RoadAccidentSvcMock) getAndPublishRoadAccidents(ctx context.Context, lastChangeID string) (string, error) {
	if mock.getAndPublishRoadAccidentsFunc == nil {
		panic("RoadAccidentSvcMock.getAndPublishRoadAccidentsFunc: method is nil but RoadAccidentSvc.getAndPublishRoadAccidents was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		LastChangeID string
	}{
		Ctx:          ctx,
		LastChangeID: lastChangeID,
	}
	mock.lockgetAndPublishRoadAccidents.Lock()
	mock.calls.getAndPublishRoadAccidents = append(mock.calls.getAndPublishRoadAccidents, callInfo)
	mock.lockgetAndPublishRoadAccidents.Unlock()
	return mock.getAndPublishRoadAccidentsFunc(ctx, lastChangeID)
}

// getAndPublishRoadAccidentsCalls gets all the calls that were made to getAndPublishRoadAccidents.
// Check the length with:
//
//	len(mockedRoadAccidentSvc.getAndPublishRoadAccidentsCalls())
func (mock *RoadAccidentSvcMock) getAndPublishRoadAccidentsCalls() []struct {
	Ctx          context.Context
	LastChangeID string
} {
	var calls []struct {
		Ctx          context.Context
		LastChangeID string
	}
	mock.lockgetAndPublishRoadAccidents.RLock()
	calls = mock.calls.getAndPublishRoadAccidents
	mock.lockgetAndPublishRoadAccidents.RUnlock()
	return calls
}

// getRoadAccidentsFromTFV calls getRoadAccidentsFromTFVFunc.
func (mock *RoadAccidentSvcMock) getRoadAccidentsFromTFV(ctx context.Context, lastChangeID string) ([]byte, error) {
	if mock.getRoadAccidentsFromTFVFunc == nil {
		panic("RoadAccidentSvcMock.getRoadAccidentsFromTFVFunc: method is nil but RoadAccidentSvc.getRoadAccidentsFromTFV was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		LastChangeID string
	}{
		Ctx:          ctx,
		LastChangeID: lastChangeID,
	}
	mock.lockgetRoadAccidentsFromTFV.Lock()
	mock.calls.getRoadAccidentsFromTFV = append(mock.calls.getRoadAccidentsFromTFV, callInfo)
	mock.lockgetRoadAccidentsFromTFV.Unlock()
	return mock.getRoadAccidentsFromTFVFunc(ctx, lastChangeID)
}

// getRoadAccidentsFromTFVCalls gets all the calls that were made to getRoadAccidentsFromTFV.
// Check the length with:
//
//	len(mockedRoadAccidentSvc.getRoadAccidentsFromTFVCalls())
func (mock *RoadAccidentSvcMock) getRoadAccidentsFromTFVCalls() []struct {
	Ctx          context.Context
	LastChangeID string
} {
	var calls []struct {
		Ctx          context.Context
		LastChangeID string
	}
	mock.lockgetRoadAccidentsFromTFV.RLock()
	calls = mock.calls.getRoadAccidentsFromTFV
	mock.lockgetRoadAccidentsFromTFV.RUnlock()
	return calls
}

// publishRoadAccidentToContextBroker calls publishRoadAccidentToContextBrokerFunc.
func (mock *RoadAccidentSvcMock) publishRoadAccidentToContextBroker(ctx context.Context, dev tfvDeviation, deleted bool) error {
	if mock.publishRoadAccidentToContextBrokerFunc == nil {
		panic("RoadAccidentSvcMock.publishRoadAccidentToContextBrokerFunc: method is nil but RoadAccidentSvc.publishRoadAccidentToContextBroker was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Dev     tfvDeviation
		Deleted bool
	}{
		Ctx:     ctx,
		Dev:     dev,
		Deleted: deleted,
	}
	mock.lockpublishRoadAccidentToContextBroker.Lock()
	mock.calls.publishRoadAccidentToContextBroker = append(mock.calls.publishRoadAccidentToContextBroker, callInfo)
	mock.lockpublishRoadAccidentToContextBroker.Unlock()
	return mock.publishRoadAccidentToContextBrokerFunc(ctx, dev, deleted)
}

// publishRoadAccidentToContextBrokerCalls gets all the calls that were made to publishRoadAccidentToContextBroker.
// Check the length with:
//
//	len(mockedRoadAccidentSvc.publishRoadAccidentToContextBrokerCalls())
func (mock *RoadAccidentSvcMock) publishRoadAccidentToContextBrokerCalls() []struct {
	Ctx     context.Context
	Dev     tfvDeviation
	Deleted bool
} {
	var calls []struct {
		Ctx     context.Context
		Dev     tfvDeviation
		Deleted bool
	}
	mock.lockpublishRoadAccidentToContextBroker.RLock()
	calls = mock.calls.publishRoadAccidentToContextBroker
	mock.lockpublishRoadAccidentToContextBroker.RUnlock()
	return calls
}
